### ISSUE TITLE
Provide more generality for later assignments

### ISSUE THREAD

**Issue by willGraham01** [UCL-COMP0233-23-24/assignment-submission-checker#10]
The current checker works well for 2023-24, which is the year it was hastily written for. However it is very clunky if the assignment for the following year has a slightly different file structure, or naming conventions.

A quick redesign of how assignments are stored and interpreted should address this. Instead of defining assignments as hard-coded objects, we will provide them as `.yaml` files with certain keywords for directories, option/compulsory files, etc.

```yaml
- name: Assignment 20YY-YY
- number: 01 # or 02 or LSA
- structure:
  - candidate_number:
    - directory: True
    - next_folder_down:
      - directory: True
      - git-root: True
      - file_1:
        - type: ".py"
        - compulsory: True
      - file_2:
        - type: ".py"
        - compulsory: False
      - report:
        - directory: True
        - file_1:
          - type: ".md"
          - compulsory: True
        - file_2:
          - type: ".pdf"
          - compulsory: False
```
